### ISSUE TITLE
Bcrypt is deprecated

### ISSUE THREAD

**Issue by FalcoSuessgott** [FalcoSuessgott/htw-berlin-webentwicklung-gruppe_04#10]
[See the following conversation](https://github.com/FalcoSuessgott/htw-berlin-webentwicklung-gruppe_04/pull/2#discussion_r312903247)

**Comment by FalcoSuessgott** [comment]
@viktorianer 
Habe mich nach Alternativen umgeschaut und eigentlich erscheint mir nur [bcryptjs](https://github.com/dcodeIO/bcrypt.js) als ausreichend. Sollte ich diese Library nutzen für das Passwordhashing?

**Comment by viktorianer** [comment]
> @viktorianer
> Habe mich nach Alternativen umgeschaut und eigentlich erscheint mir nur [bcryptjs](https://github.com/dcodeIO/bcrypt.js) als ausreichend. Sollte ich diese Library nutzen für das Passwordhashing?

Nein, das gilt für alle - Scrypt und besser ist erlaubt.
https://www.tarsnap.com/scrypt.html

> The scrypt key derivation function was originally developed for use in the Tarsnap online backup system and is designed to be far more secure against hardware brute-force attacks than alternative functions such as PBKDF2 or bcrypt.

**Comment by FalcoSuessgott** [comment]
[fix in #pr20](https://github.com/FalcoSuessgott/htw-berlin-webentwicklung-gruppe_04/pull/20)
